# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-14 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('source', models.CharField(max_length=50)),
                ('pub_time', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image_url', models.CharField(max_length=100)),
            ],
        ),
    ]
