# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-18 12:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 10, 18, 12, 17, 17, 263384)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='created_time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 10, 18, 12, 17, 47, 469995)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='created_time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 10, 18, 12, 18, 4, 19411)),
            preserve_default=False,
        ),
    ]
