# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-19 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0003_auto_20171019_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='buy_nums',
        ),
    ]
