# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-19 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0004_remove_course_buy_nums'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('thumb_image_url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='isRecommend',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
