# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-19 15:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0005_auto_20171019_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='isRecommend',
            new_name='is_recommend',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 19, 15, 25, 12, 209540)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisement',
            name='is_show',
            field=models.BooleanField(default=datetime.datetime(2017, 10, 19, 15, 25, 19, 466177)),
            preserve_default=False,
        ),
    ]
