# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-25 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0006_auto_20171019_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video_cover_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_thumb_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
