# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-13 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinancialNews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialnews',
            name='url',
            field=models.CharField(default='http://stock.qq.com', max_length=256),
            preserve_default=False,
        ),
    ]
