# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-13 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinancialNews', '0002_financialnews_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialnews',
            name='url',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
