# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-13 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinancialNews', '0003_auto_20170913_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialnews',
            name='image_url',
            field=models.CharField(default='empty', max_length=100),
            preserve_default=False,
        ),
    ]
