# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-24 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('device_type', models.IntegerField()),
                ('device_userID', models.IntegerField()),
            ],
        ),
    ]
