# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-25 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Push', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ('user_id',)},
        ),
        migrations.RenameField(
            model_name='device',
            old_name='device_id',
            new_name='device_token',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='device_userID',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('iOS', 'iOS设备'), ('Android', '安卓设备')], default='iOS', max_length=10),
        ),
    ]
