# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-29 08:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Push', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='update_time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 9, 29, 8, 3, 29, 841205, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
