# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-10-10 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Push', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenWebMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert', models.CharField(max_length=500)),
                ('push_id', models.CharField(max_length=100)),
                ('custom_data', models.CharField(max_length=1000)),
                ('url', models.CharField(max_length=500)),
                ('devices', models.ManyToManyField(to='Push.Device')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
