swagger: '2.0'
info:
  title: 1234TV API
  description: |
    相关常量枚举:
        
        接口返回状态码(code):  
          OK = ("操作成功",0)
          SERIALIZER_ERROR = ("序列化失败",1)
          OBJECT_NOT_EXSIT = ("对象不存在",2)
          PUSH_FAILED = ("推送失败",3)

        自定义数据动作类型(action):
          PUSH_ACTION_OPEN_WEBVIEW = 1   #打开Web网页
          PUSH_ACTION_OPEN_LIVEROOM = 2  #打开直播间
          PUSH_ACTION_OPEN_TEAMHALL = 3  #打开团队首页
          <未完待续>
      
  version: "1.0.0"
# the domain of the service
host: localhost:8000
# array of all schemes that your API supports
schemes:
  - http
  - https
# will be prefixed to all paths
basePath: /api/v1
produces:
  - application/json
paths:
  /push/list:
    get:
      tags:
        - Push


  /push/register_device:
    post:
      summary: 注册推送设备(用户登录成功后调用)
      parameters:
        - name: device_token
          in: formData
          required: true
          type: string
          description: 设备唯一标示符
        - name: device_type
          in: formData
          enum: ['iOS','Android']
          required: true
          type: string
          description: 设备类型
        - name: user_id
          in: formData
          type: string
          required: true
          description: 设备绑定的用户ID
      tags:
        - Push

  /push/unregister_device:
    post:
      summary: 删除已注册的设备(用户退出登录后调用)
      parameters:
        - name: device_token
          in: formData
          required: true
          type: string
          description: 设备唯一标示符
      tags:
        - Push

  /push/live:
    post:
      summary: 直播间直播通知
      parameters:
        - name: user_ids
          in: formData
          type: string
          required: true
          description: 推送的用户id列表(逗号分隔,sample:1,2,3)
        - name: room_id
          in: formData
          type: string
          required: true
          description: 房间ID
        - name: eng_name
          in: formData
          type: string
          description: 团队名称
        - name: alert
          in: formData
          type: string
          description: 弹框标题
      tags:
        - Push

  /push/web:
    post:
      summary: 打开网页通知
      parameters:
        - name: user_ids
          in: formData
          type: string
          required: true
          description: 推送的用户id列表(逗号分隔,sample:1,2,3)
        - name: url
          in: formData
          type: string
          required: true
          description: url地址
        - name: alert
          in: formData
          type: string
          description: 弹框标题
      tags:
        - Push

  /push/team:
    post:
      summary: 进入团队首页
      parameters:
        - name: user_ids
          in: formData
          type: string
          required: true
          description: 推送的用户id列表(逗号分隔,sample:1,2,3)
        - name: eng_name
          in: formData
          type: string
          required: true
          description: 团队英文名称
        - name: alert
          in: formData
          type: string
          description: 弹框标题
      tags:
        - Push


  /news/list:
    get:
      summary: 资讯列表
      parameters:
        - name: news_id
          in: query
          type: integer
          required: true
          description: 资讯ID,传0获取最新的数据
        - name: offset
          in: query
          type: integer
          description: 偏移量,默认20
      tags:
        - News

  /news/detail:
    get:
      summary: 资讯详情页
      parameters:
        - name: news_id
          in: query
          type: integer
          required: true
          description: 资讯ID
      tags:
        - News